### PR TITLE
Fix bug in storing UniqueClassList in Storage

### LINKED ISSUE #7: Add a class
As a TA I can so that I can keep track of my classes.

### PR DESCRIPTION
**Pull request by songgthu**
The bug was the storage did not read the class list data correctly, and it replace the class list data as empty list when the app is run.

Solution:
- Add setClasses() function in UniqueClassList class
- Update the resetData function in the EduTrack class (which is responsible for updating the data) to call setClasses() in order to load the updated class list.

### CODE REVIEW

**Review by sudarshan2401 — APPROVED** [review]
LGTM! Nit: In the future it would be better to specify what the bug was for more clarity!

**Comment by seanpzk** [comment]
LGTM!

**Review by seanpzk — APPROVED** [review]
LGTM!

**Comment by songgthu** [comment]
> LGTM! Nit: In the future it would be better to specify what the bug was for more clarity!

Thanks for pointing that out, I have added the description of the bug and how I solved it.

**Pull request merged**
